apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache-scheduler
  template:
    metadata:
      labels:
        app: cache-scheduler
    spec:
      containers:
      - name: cache-scheduler
        image: 654654308839.dkr.ecr.ap-northeast-2.amazonaws.com/weddy/cache_scheduler:latest
        ports:
        - containerPort: 8080
