apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 654654308839.dkr.ecr.ap-northeast-2.amazonaws.com/weddy/frontend:latest
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: frontend-env
