apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule
  namespace: msa
  labels:
    app: schedule
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schedule
  template:
    metadata:
      labels:
        app: schedule
    spec:
      containers:
      - name: schedule
        image: siokim002/schedule:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "300m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "700Mi"
