apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  project: default  # 기본 project 사용
  source:
    repoURL: https://github.com/zion0425/weddy-gitops
    targetRevision: HEAD
    path: base/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
