apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schedule
  template:
    metadata:
      labels:
        app: schedule
    spec:
      containers:
      - name: schedule
        image: 654654308839.dkr.ecr.ap-northeast-2.amazonaws.com/weddy/schedule:205
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
