apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: schedule
  template:
    metadata:
      labels:
        app: schedule
    spec:
      containers:
      - name: schedule
        image: 654654308839.dkr.ecr.ap-northeast-2.amazonaws.com/weddy/schedule:latest
        ports:
        - containerPort: 8080
