apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: 654654308839.dkr.ecr.ap-northeast-2.amazonaws.com/weddy/product:latest
        ports:
        - containerPort: 8080
